"""Initial schema: runs, conversations, themes, approval_items.

Revision ID: 0001
Revises:
Create Date: 2026-08-09

Written by hand rather than autogenerated so the pgvector column and the enum types are
explicit. Autogenerate does not reliably emit CREATE TYPE for native enums on a first
migration, and it renders Vector as NULL.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Must match settings.EMBEDDING_DIM. Changing the setting alone will not alter an
# existing column — that needs a follow-up migration.
EMBEDDING_DIM = 384

RUN_STATUS = (
    "PENDING", "INGESTING", "CLASSIFYING", "EXTRACTING", "THEMING", "ANONYMIZING",
    "COMPARING", "DRAFTING", "AWAITING_APPROVAL", "APPROVED", "UPLOADING", "COMPLETE",
    "FAILED", "PAUSED",
)
TREND = ("GREW", "SHRANK", "STABLE", "NEW", "RESOLVED", "UNKNOWN")
ITEM_TYPE = ("THEME", "QUOTE", "FINDING", "UPDATE")
APPROVAL_STATUS = ("PENDING", "APPROVED", "REJECTED")


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    run_status = postgresql.ENUM(*RUN_STATUS, name="run_status", create_type=False)
    trend = postgresql.ENUM(*TREND, name="trend_direction", create_type=False)
    item_type = postgresql.ENUM(*ITEM_TYPE, name="approval_item_type", create_type=False)
    approval_status = postgresql.ENUM(*APPROVAL_STATUS, name="approval_status", create_type=False)
    for enum in (run_status, trend, item_type, approval_status):
        enum.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "runs",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", run_status, nullable=False),
        sa.Column("current_stage", sa.String(64)),
        sa.Column("stage_started_at", sa.DateTime(timezone=True)),
        sa.Column("input_path", sa.Text(), nullable=False),
        sa.Column("last_digest_path", sa.Text()),
        sa.Column("quarter_label", sa.String(32)),
        sa.Column("superdocs_session_id", sa.String(256)),
        sa.Column("superdocs_document_id", sa.String(128)),
        sa.Column("superdocs_job_id", sa.String(128)),
        sa.Column("checkpoint_data", postgresql.JSONB(), nullable=False),
        sa.Column("cost_report", postgresql.JSONB(), nullable=False),
        sa.Column("decision_log", postgresql.JSONB(), nullable=False),
        sa.Column("error_message", sa.Text()),
        sa.Column("export_path", sa.Text()),
    )
    op.create_index("ix_runs_status", "runs", ["status"])
    op.create_index("ix_runs_superdocs_session_id", "runs", ["superdocs_session_id"])

    op.create_table(
        "themes",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("run_id", postgresql.UUID(as_uuid=True),
                  sa.ForeignKey("runs.id", ondelete="CASCADE"), nullable=False),
        sa.Column("name", sa.String(256), nullable=False),
        sa.Column("description", sa.Text()),
        sa.Column("volume_count", sa.Integer(), nullable=False),
        sa.Column("volume_share", sa.Float()),
        sa.Column("embedding", Vector(EMBEDDING_DIM)),
        sa.Column("prior_quarter_count", sa.Integer()),
        sa.Column("prior_theme_name", sa.String(256)),
        sa.Column("match_similarity", sa.Float()),
        sa.Column("growth_rate", sa.Float()),
        sa.Column("volume_trend", trend, nullable=False),
        sa.Column("representative_quotes", postgresql.JSONB()),
        sa.Column("evidence_refs", postgresql.JSONB()),
        sa.Column("confidence_note", sa.Text()),
    )
    op.create_index("ix_themes_run_id", "themes", ["run_id"])
    op.create_index("ix_themes_run_volume", "themes", ["run_id", "volume_count"])

    op.create_table(
        "conversations",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("run_id", postgresql.UUID(as_uuid=True),
                  sa.ForeignKey("runs.id", ondelete="CASCADE"), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("source_file", sa.String(512), nullable=False),
        sa.Column("source_line", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True)),
        sa.Column("embedding", Vector(EMBEDDING_DIM)),
        sa.Column("classified_type", sa.String(64)),
        sa.Column("is_relevant", sa.Boolean(), nullable=False),
        sa.Column("classification_reason", sa.Text()),
        sa.Column("extracted_facts", postgresql.JSONB()),
        sa.Column("theme_id", postgresql.UUID(as_uuid=True),
                  sa.ForeignKey("themes.id", ondelete="SET NULL")),
        sa.Column("injection_flagged", sa.Boolean(), nullable=False),
        sa.UniqueConstraint("run_id", "source_file", "source_line", name="uq_conv_source"),
    )
    op.create_index("ix_conversations_run_id", "conversations", ["run_id"])
    op.create_index("ix_conversations_classified_type", "conversations", ["classified_type"])
    op.create_index("ix_conversations_run_theme", "conversations", ["run_id", "theme_id"])

    op.create_table(
        "approval_items",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("run_id", postgresql.UUID(as_uuid=True),
                  sa.ForeignKey("runs.id", ondelete="CASCADE"), nullable=False),
        sa.Column("item_type", item_type, nullable=False),
        sa.Column("content", postgresql.JSONB(), nullable=False),
        sa.Column("status", approval_status, nullable=False),
        sa.Column("reviewer_note", sa.Text()),
        sa.Column("decided_at", sa.DateTime(timezone=True)),
        sa.Column("superdocs_change_id", sa.String(128)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_approval_items_run_id", "approval_items", ["run_id"])
    op.create_index("ix_approval_run_status", "approval_items", ["run_id", "status"])

    # Approximate-nearest-neighbour index for QoQ theme matching. ivfflat needs data to
    # build good lists, so this is intentionally small — rebuild after a large backfill.
    op.execute(
        "CREATE INDEX ix_themes_embedding ON themes "
        "USING ivfflat (embedding vector_cosine_ops) WITH (lists = 10)"
    )


def downgrade() -> None:
    op.drop_table("approval_items")
    op.drop_table("conversations")
    op.drop_table("themes")
    op.drop_table("runs")
    for name in ("approval_status", "approval_item_type", "trend_direction", "run_status"):
        op.execute(f"DROP TYPE IF EXISTS {name}")
